sudo: false
language: node_js
cache:
  directories:
  - ./node_modules/
notifications:
  email: false
node_js:
  - '10'
  - '8'
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run test-build
